// ─────────────────────────────────────────────────────────────────────────────
// CONTRATO COPIADO DO SITE — Nível 1 ("copiar com disciplina"), ver
// weracha-site/docs/pendente (doc do app) §"Compartilhar contrato".
//
// Fonte da verdade: weracha-site/lib/api/codigosErro.ts (repo do site).
// Ao mudar lá, reflita aqui e rode `npm test` — o teste em
// __tests__/contrato-codigos-erro.test.ts trava a lista e quebra no desalinho.
//
// Diferença de forma proposital: o site declara `CodigoErro` como union type;
// aqui é um array `readonly` pra dar pra checar em runtime (o teste precisa).
// Os VALORES é que são o contrato.
// ─────────────────────────────────────────────────────────────────────────────

export const CODIGOS_ERRO = [
  // autenticação / autorização
  "NAO_AUTENTICADO",
  "SOMENTE_MASTER",
  "GRUPO_NAO_MEMBRO",
  "GRUPO_REQUER_ADMIN",
  "GRUPO_REQUER_ADMIN_OU_MASTER",
  "TOKEN_ACESSO_AUSENTE",
  "TOKEN_ACESSO_INVALIDO",

  // validação de entrada
  "CORPO_INVALIDO",
  "CAMPO_INVALIDO",

  // erro genérico / infra
  "ERRO_INTERNO",
  "CSRF_ORIGEM_INVALIDA",

  // telefone / SMS
  "TELEFONE_INVALIDO",
  "SMS_NUMERO_INVALIDO",
  "SMS_NUMERO_NAO_ELEGIVEL",
  "SMS_LIMITE_EXCEDIDO",
  "SMS_RESTRICAO_CONTA",
  "SMS_FALHA_ENVIO",
  "SMS_NAO_CONFIGURADO",
  "SMS_DESABILITADO",

  // auth / conta
  "CONTA_BLOQUEADA",
  "TELEFONE_JA_VERIFICADO",
  "TELEFONE_NAO_VERIFICADO",
  "TELEFONE_NAO_CADASTRADO",
  "NOME_OBRIGATORIO_CADASTRO",
  "CODIGO_COOLDOWN",
  "CODIGO_LIMITE_DIARIO",
  "CODIGO_NAO_SOLICITADO",
  "CODIGO_EXPIRADO",
  "CODIGO_TENTATIVAS_EXCEDIDAS",
  "CODIGO_INCORRETO",
  "SENHA_MUITO_CURTA",
  "LOGIN_BLOQUEADO",
  "SENHA_INCORRETA",
  "SENHA_NAO_DEFINIDA",

  // exclusão de conta
  "EXCLUSAO_JA_EM_ANDAMENTO",
  "EXCLUSAO_BLOQUEADA_DONO_DE_GRUPO",
  "TELEFONE_SEM_CADASTRO",
  "SOLICITACAO_EXCLUSAO_NAO_ENCONTRADA",
  "SOLICITACAO_EXCLUSAO_JA_RESOLVIDA",

  // jogadores
  "NOME_OBRIGATORIO",
  "EMAIL_INVALIDO",
  "EMAIL_OBRIGATORIO_PARA_NOTIFICACAO",
  "DATA_NASCIMENTO_INVALIDA",
  "DATA_NASCIMENTO_NO_FUTURO",
  "DATA_NASCIMENTO_TORNARIA_MAIOR",
  "FOTO_URL_INVALIDA",
  "JOGADOR_NAO_ENCONTRADO",
  "JOGADOR_NAO_ENCONTRADO_NO_GRUPO",
  "JOGADOR_AUTOACAO_BLOQUEADA",
  "JOGADOR_DONO_DE_GRUPO",
  "JOGADOR_CRIOU_QUADRA",
  "JOGADOR_REGISTROU_GOLS",
  "JOGADOR_REGISTROU_LANCES",
  "JOGADOR_CRIOU_ENQUETE",
  "JOGADOR_TEM_VINCULOS",
  "TELEFONE_OBRIGATORIO",
  "JOGADOR_FORA_DO_GRUPO",

  // posições
  "POSICAO_NOME_OBRIGATORIO",
  "POSICAO_DESCRICAO_OBRIGATORIA",
  "POSICAO_JA_CADASTRADA",
  "POSICAO_NAO_ENCONTRADA",
  "POSICAO_INVALIDA_PARA_ESPORTE",

  // parceiros
  "PARCEIRO_NAO_ENCONTRADO",
  "PARCEIRO_CAMPOS_OBRIGATORIOS",
  "PARCEIRO_LINK_INVALIDO",

  // contato / ouvidoria
  "MENSAGEM_CONTATO_NAO_ENCONTRADA",
  "CONTATO_ROBO_NAO_CONFIRMADO",
  "CONTATO_TITULO_OBRIGATORIO",
  "CONTATO_TITULO_MUITO_LONGO",
  "CONTATO_DESCRICAO_OBRIGATORIA",
  "CONTATO_DESCRICAO_MUITO_LONGA",
  "CONTATO_NOME_OBRIGATORIO",
  "CONTATO_NOME_MUITO_LONGO",
  "CONTATO_LIMITE_EXCEDIDO",

  // quadras
  "QUADRA_CAMPOS_OBRIGATORIOS",
  "QUADRA_ESPORTE_OBRIGATORIO",
  "QUADRA_STATUS_INVALIDO",
  "QUADRA_NAO_ENCONTRADA",
  "QUADRA_INCOMPATIVEL_COM_ESPORTE",
  "QUADRA_PENDENTE_APROVACAO",

  // esportes
  "ESPORTE_NOME_OBRIGATORIO",
  "ESPORTE_DESCRICAO_OBRIGATORIA",
  "ESPORTE_JA_CADASTRADO",
  "ESPORTE_NAO_ENCONTRADO",

  // grupos / membros / partidas
  "JOGADOR_JA_NO_GRUPO",
  "GRUPO_SOMENTE_DONO",
  "JOGADOR_EXCLUSAO_PENDENTE_BLOQUEIA_PROMOCAO",
  "GRUPO_DONO_NAO_REBAIXAVEL",
  "GRUPO_DONO_NAO_PODE_DEIXAR_ADMIN",
  "GRUPO_DONO_NAO_REMOVIVEL",
  "GRUPO_DONO_DEVE_TRANSFERIR_ANTES_DE_SAIR",
  "GRUPO_NAO_ENCONTRADO",
  "GRUPO_TRANSFERENCIA_MESMO_DONO",
  "GRUPO_NOVO_DONO_DEVE_SER_ADMIN",
  "GRUPO_COM_RESULTADO_NAO_EXCLUIVEL",
  "PARTIDA_COM_RESULTADO_NAO_CANCELAVEL",
  "PARTIDA_SOMENTE_CANCELADA_EXCLUIVEL",
  "PARTIDA_COM_RESULTADO_NAO_EXCLUIVEL",
  "PARTIDA_HORARIO_NO_PASSADO",
  "EXCLUSAO_PENDENTE_BLOQUEIA_CRIAR_GRUPO",
  "GRUPO_DATA_OBRIGATORIA",
  "PARTIDA_AVULSA_REQUER_GRUPO_AVULSO",

  // convites
  "CONVITE_REQUER_LOGIN",
  "CONVITE_INVALIDO",

  // enquetes
  "ENQUETE_PERGUNTA_OBRIGATORIA",
  "ENQUETE_MINIMO_DUAS_OPCOES",
  "ENQUETE_LIMITE_ATIVA_POR_JOGADOR",
  "ENQUETE_NAO_ENCONTRADA",
  "ENQUETE_EDICAO_REQUER_CRIADOR_OU_ADMIN",
  "ENQUETE_JA_TEM_VOTO",
  "ENQUETE_ENCERRADA",
  "ENQUETE_OPCAO_INVALIDA",
  "ENQUETE_VOTO_SECRETO",

  // resenha
  "REPLAY_NAO_ENCONTRADO",
  "GOL_JA_CANCELADO",
  "REPLAY_SOMENTE_LOCAL",
  "PERFIL_SEM_DATA_NASCIMENTO",
  "COMENTARIO_BLOQUEADO_MENOR_IDADE",
  "PARTIDA_CANCELADA",
  "COMENTARIO_TEXTO_OBRIGATORIO",
  "COMENTARIO_MUITO_LONGO",
  "COMENTARIO_COOLDOWN",
  "COMENTARIO_NAO_PROPRIO",
  "COMENTARIO_JANELA_EXCLUSAO_EXPIRADA",

  // ao vivo / gols
  "LANCES_DESATIVADOS",
  "PRAZO_EDICAO_GOL_EXPIRADO",
  "GOL_REDUCAO_NAO_PERMITIDA",
  "GOL_NAO_ENCONTRADO",
  "GOL_NAO_CANCELADO",
  "GOL_CANCELADO_MIGRACAO_BLOQUEADA",
  "GOL_JA_DESSE_JOGADOR",
  "PARTIDA_NAO_ENCONTRADA",

  // resultados / sorteio
  "SORTEIO_FALHOU",
  "PARTIDA_ENCERRADA_SORTEIO_BLOQUEADO",

  // pedido de replay
  "PEDIDO_REPLAY_NAO_ENCONTRADO",

  // score
  "SCORE_CONGELADO",
] as const;

export type CodigoErro = (typeof CODIGOS_ERRO)[number];

const CODIGOS_SET = new Set<string>(CODIGOS_ERRO);

/** `true` se a string é um código de erro conhecido do contrato. */
export function ehCodigoErro(valor: unknown): valor is CodigoErro {
  return typeof valor === "string" && CODIGOS_SET.has(valor);
}

// Status HTTP por código — só as entradas que fogem do padrão 422 (regra de
// negócio genérica). Espelha STATUS_POR_CODIGO do site; usado só como dica pra
// telemetria/log do app, o servidor é quem manda o status de verdade.
const STATUS_POR_CODIGO: Partial<Record<CodigoErro, number>> = {
  NAO_AUTENTICADO: 401,
  TOKEN_ACESSO_AUSENTE: 401,
  TOKEN_ACESSO_INVALIDO: 401,
  CONTA_BLOQUEADA: 401,
  CODIGO_NAO_SOLICITADO: 401,
  CODIGO_EXPIRADO: 401,
  CODIGO_INCORRETO: 401,
  SENHA_INCORRETA: 401,
  CONVITE_REQUER_LOGIN: 401,

  SOMENTE_MASTER: 403,
  GRUPO_NAO_MEMBRO: 403,
  GRUPO_REQUER_ADMIN: 403,
  GRUPO_REQUER_ADMIN_OU_MASTER: 403,
  CSRF_ORIGEM_INVALIDA: 403,
  GRUPO_SOMENTE_DONO: 403,
  ENQUETE_EDICAO_REQUER_CRIADOR_OU_ADMIN: 403,
  COMENTARIO_BLOQUEADO_MENOR_IDADE: 403,
  COMENTARIO_NAO_PROPRIO: 403,

  CORPO_INVALIDO: 400,
  CAMPO_INVALIDO: 400,
  TELEFONE_INVALIDO: 400,
  SMS_NUMERO_INVALIDO: 400,

  JOGADOR_NAO_ENCONTRADO: 404,
  JOGADOR_NAO_ENCONTRADO_NO_GRUPO: 404,
  POSICAO_NAO_ENCONTRADA: 404,
  PARCEIRO_NAO_ENCONTRADO: 404,
  MENSAGEM_CONTATO_NAO_ENCONTRADA: 404,
  QUADRA_NAO_ENCONTRADA: 404,
  ESPORTE_NAO_ENCONTRADO: 404,
  GRUPO_NAO_ENCONTRADO: 404,
  CONVITE_INVALIDO: 404,
  ENQUETE_NAO_ENCONTRADA: 404,
  REPLAY_NAO_ENCONTRADO: 404,
  GOL_NAO_ENCONTRADO: 404,
  PARTIDA_NAO_ENCONTRADA: 404,
  SOLICITACAO_EXCLUSAO_NAO_ENCONTRADA: 404,
  PEDIDO_REPLAY_NAO_ENCONTRADO: 404,
  TELEFONE_NAO_CADASTRADO: 404,

  TELEFONE_JA_VERIFICADO: 409,
  EXCLUSAO_JA_EM_ANDAMENTO: 409,
  SOLICITACAO_EXCLUSAO_JA_RESOLVIDA: 409,
  POSICAO_JA_CADASTRADA: 409,
  ESPORTE_JA_CADASTRADO: 409,
  QUADRA_PENDENTE_APROVACAO: 409,
  JOGADOR_JA_NO_GRUPO: 409,
  ENQUETE_LIMITE_ATIVA_POR_JOGADOR: 409,
  GOL_JA_CANCELADO: 409,
  GOL_JA_DESSE_JOGADOR: 409,
  PARTIDA_CANCELADA: 409,
  PARTIDA_ENCERRADA_SORTEIO_BLOQUEADO: 409,

  CODIGO_COOLDOWN: 429,
  CODIGO_LIMITE_DIARIO: 429,
  CODIGO_TENTATIVAS_EXCEDIDAS: 429,
  LOGIN_BLOQUEADO: 429,
  SMS_LIMITE_EXCEDIDO: 429,
  COMENTARIO_COOLDOWN: 429,
  CONTATO_LIMITE_EXCEDIDO: 429,

  ERRO_INTERNO: 500,
  SMS_FALHA_ENVIO: 500,
  SMS_NAO_CONFIGURADO: 500,

  SMS_DESABILITADO: 503,
};

const STATUS_PADRAO = 422;

export function statusDoCodigo(codigo: CodigoErro): number {
  return STATUS_POR_CODIGO[codigo] ?? STATUS_PADRAO;
}
