// Ícones do app: mesma lib (lucide) e mesmos nomes do site. Reexport central
// pra ter um lugar só listando "o que o app usa" e um ponto único de troca,
// espelhando o bloco de import de `weracha-site/components/*`.
//
// Uso: `import { Users } from "@/ui/Icone"` e `<Users size={18} color={cores.teal} />`
// (mesma API de props do site: size / color / strokeWidth).

export type { LucideIcon } from "lucide-react-native";

export {
  // navbar / navegação
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  ArrowRight,
  ArrowLeft,
  ExternalLink,
  MoreHorizontal,
  EllipsisVertical,
  // menu principal
  CircleUserRound,
  Users,
  Goal,
  Video,
  BarChart3,
  Store,
  Mail,
  Shuffle,
  LogOut,
  Settings,
  Trophy,
  LandPlot,
  Handshake,
  Inbox,
  // ações
  Plus,
  Minus,
  Check,
  Play,
  Pause,
  Pencil,
  Trash2,
  Search,
  Share2,
  RefreshCw,
  RotateCcw,
  Copy,
  Send,
  Download,
  Sparkles,
  Timer,
  ArrowDownAZ,
  // acesso
  LogIn,
  UserPlus,
  KeyRound,
  Eye,
  EyeOff,
  MessageSquareText,
  MessageCircle,
  // status / avisos
  Clock,
  Calendar,
  CalendarDays,
  CalendarClock,
  MapPin,
  MapPinPlus,
  TriangleAlert,
  Info,
  Lock,
  Crown,
  ShieldCheck,
  Star,
  Radio,
  Flame,
  Camera,
  Wallet,
  Phone,
  Goal as Bola,
} from "lucide-react-native";
